// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameObject struct {
	ID                   string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Tags                 []*TagObject     `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty"`
	Description          *LocalizedString `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Name                 string           `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Title                string           `protobuf:"bytes,5,opt,name=Title,proto3" json:"Title,omitempty"`
	Developer            *LinkObject      `protobuf:"bytes,6,opt,name=Developer,proto3" json:"Developer,omitempty"`
	ReleaseDate          string           `protobuf:"bytes,7,opt,name=ReleaseDate,proto3" json:"ReleaseDate,omitempty"`
	GenreMain            *TagObject       `protobuf:"bytes,8,opt,name=GenreMain,proto3" json:"GenreMain,omitempty"`
	Genres               []*TagObject     `protobuf:"bytes,9,rep,name=Genres,proto3" json:"Genres,omitempty"`
	Platforms            *Platforms       `protobuf:"bytes,10,opt,name=Platforms,proto3" json:"Platforms,omitempty"`
	Requirements         *Requirements    `protobuf:"bytes,11,opt,name=Requirements,proto3" json:"Requirements,omitempty"`
	Languages            *Languages       `protobuf:"bytes,12,opt,name=Languages,proto3" json:"Languages,omitempty"`
	DisplayRemainingTime bool             `protobuf:"varint,13,opt,name=DisplayRemainingTime,proto3" json:"DisplayRemainingTime,omitempty"`
	FeaturesControl      string           `protobuf:"bytes,14,opt,name=FeaturesControl,proto3" json:"FeaturesControl,omitempty"`
	Features             []string         `protobuf:"bytes,15,rep,name=Features,proto3" json:"Features,omitempty"`
	Media                *Media           `protobuf:"bytes,16,opt,name=Media,proto3" json:"Media,omitempty"`
	Ratings              *Ratings         `protobuf:"bytes,17,opt,name=Ratings,proto3" json:"Ratings,omitempty"`
	Tagline              *LocalizedString `protobuf:"bytes,18,opt,name=Tagline,proto3" json:"Tagline,omitempty"`
	GameSite             string           `protobuf:"bytes,19,opt,name=GameSite,proto3" json:"GameSite,omitempty"`
	Reviews              []*Review        `protobuf:"bytes,20,rep,name=Reviews,proto3" json:"Reviews,omitempty"`
	Publisher            *LinkObject      `protobuf:"bytes,21,opt,name=Publisher,proto3" json:"Publisher,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GameObject) Reset()         { *m = GameObject{} }
func (m *GameObject) String() string { return proto.CompactTextString(m) }
func (*GameObject) ProtoMessage()    {}
func (*GameObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *GameObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameObject.Unmarshal(m, b)
}
func (m *GameObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameObject.Marshal(b, m, deterministic)
}
func (m *GameObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameObject.Merge(m, src)
}
func (m *GameObject) XXX_Size() int {
	return xxx_messageInfo_GameObject.Size(m)
}
func (m *GameObject) XXX_DiscardUnknown() {
	xxx_messageInfo_GameObject.DiscardUnknown(m)
}

var xxx_messageInfo_GameObject proto.InternalMessageInfo

func (m *GameObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *GameObject) GetTags() []*TagObject {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GameObject) GetDescription() *LocalizedString {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *GameObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GameObject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GameObject) GetDeveloper() *LinkObject {
	if m != nil {
		return m.Developer
	}
	return nil
}

func (m *GameObject) GetReleaseDate() string {
	if m != nil {
		return m.ReleaseDate
	}
	return ""
}

func (m *GameObject) GetGenreMain() *TagObject {
	if m != nil {
		return m.GenreMain
	}
	return nil
}

func (m *GameObject) GetGenres() []*TagObject {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *GameObject) GetPlatforms() *Platforms {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *GameObject) GetRequirements() *Requirements {
	if m != nil {
		return m.Requirements
	}
	return nil
}

func (m *GameObject) GetLanguages() *Languages {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *GameObject) GetDisplayRemainingTime() bool {
	if m != nil {
		return m.DisplayRemainingTime
	}
	return false
}

func (m *GameObject) GetFeaturesControl() string {
	if m != nil {
		return m.FeaturesControl
	}
	return ""
}

func (m *GameObject) GetFeatures() []string {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *GameObject) GetMedia() *Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *GameObject) GetRatings() *Ratings {
	if m != nil {
		return m.Ratings
	}
	return nil
}

func (m *GameObject) GetTagline() *LocalizedString {
	if m != nil {
		return m.Tagline
	}
	return nil
}

func (m *GameObject) GetGameSite() string {
	if m != nil {
		return m.GameSite
	}
	return ""
}

func (m *GameObject) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *GameObject) GetPublisher() *LinkObject {
	if m != nil {
		return m.Publisher
	}
	return nil
}

type Review struct {
	PressName            string   `protobuf:"bytes,1,opt,name=PressName,proto3" json:"PressName,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty"`
	Score                string   `protobuf:"bytes,3,opt,name=Score,proto3" json:"Score,omitempty"`
	Quote                string   `protobuf:"bytes,4,opt,name=Quote,proto3" json:"Quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetPressName() string {
	if m != nil {
		return m.PressName
	}
	return ""
}

func (m *Review) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Review) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *Review) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

type Ratings struct {
	PEGI                 *RatingInfo `protobuf:"bytes,1,opt,name=PEGI,proto3" json:"PEGI,omitempty"`
	BBFC                 *RatingInfo `protobuf:"bytes,2,opt,name=BBFC,proto3" json:"BBFC,omitempty"`
	CERO                 *RatingInfo `protobuf:"bytes,3,opt,name=CERO,proto3" json:"CERO,omitempty"`
	ESRB                 *RatingInfo `protobuf:"bytes,4,opt,name=ESRB,proto3" json:"ESRB,omitempty"`
	USK                  *RatingInfo `protobuf:"bytes,5,opt,name=USK,proto3" json:"USK,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Ratings) Reset()         { *m = Ratings{} }
func (m *Ratings) String() string { return proto.CompactTextString(m) }
func (*Ratings) ProtoMessage()    {}
func (*Ratings) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Ratings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ratings.Unmarshal(m, b)
}
func (m *Ratings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ratings.Marshal(b, m, deterministic)
}
func (m *Ratings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ratings.Merge(m, src)
}
func (m *Ratings) XXX_Size() int {
	return xxx_messageInfo_Ratings.Size(m)
}
func (m *Ratings) XXX_DiscardUnknown() {
	xxx_messageInfo_Ratings.DiscardUnknown(m)
}

var xxx_messageInfo_Ratings proto.InternalMessageInfo

func (m *Ratings) GetPEGI() *RatingInfo {
	if m != nil {
		return m.PEGI
	}
	return nil
}

func (m *Ratings) GetBBFC() *RatingInfo {
	if m != nil {
		return m.BBFC
	}
	return nil
}

func (m *Ratings) GetCERO() *RatingInfo {
	if m != nil {
		return m.CERO
	}
	return nil
}

func (m *Ratings) GetESRB() *RatingInfo {
	if m != nil {
		return m.ESRB
	}
	return nil
}

func (m *Ratings) GetUSK() *RatingInfo {
	if m != nil {
		return m.USK
	}
	return nil
}

type RatingInfo struct {
	AgeRestrict          int32    `protobuf:"varint,1,opt,name=AgeRestrict,proto3" json:"AgeRestrict,omitempty"`
	DisplayOnlineNotice  bool     `protobuf:"varint,2,opt,name=DisplayOnlineNotice,proto3" json:"DisplayOnlineNotice,omitempty"`
	ShowAgeRestrict      bool     `protobuf:"varint,3,opt,name=ShowAgeRestrict,proto3" json:"ShowAgeRestrict,omitempty"`
	Rating               string   `protobuf:"bytes,4,opt,name=Rating,proto3" json:"Rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatingInfo) Reset()         { *m = RatingInfo{} }
func (m *RatingInfo) String() string { return proto.CompactTextString(m) }
func (*RatingInfo) ProtoMessage()    {}
func (*RatingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *RatingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatingInfo.Unmarshal(m, b)
}
func (m *RatingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatingInfo.Marshal(b, m, deterministic)
}
func (m *RatingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatingInfo.Merge(m, src)
}
func (m *RatingInfo) XXX_Size() int {
	return xxx_messageInfo_RatingInfo.Size(m)
}
func (m *RatingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RatingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RatingInfo proto.InternalMessageInfo

func (m *RatingInfo) GetAgeRestrict() int32 {
	if m != nil {
		return m.AgeRestrict
	}
	return 0
}

func (m *RatingInfo) GetDisplayOnlineNotice() bool {
	if m != nil {
		return m.DisplayOnlineNotice
	}
	return false
}

func (m *RatingInfo) GetShowAgeRestrict() bool {
	if m != nil {
		return m.ShowAgeRestrict
	}
	return false
}

func (m *RatingInfo) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

type Media struct {
	CoverImage           *LocalizedString      `protobuf:"bytes,1,opt,name=CoverImage,proto3" json:"CoverImage,omitempty"`
	CoverVideo           *LocalizedString      `protobuf:"bytes,2,opt,name=CoverVideo,proto3" json:"CoverVideo,omitempty"`
	Trailers             *LocalizedStringArray `protobuf:"bytes,3,opt,name=Trailers,proto3" json:"Trailers,omitempty"`
	Screenshots          *LocalizedStringArray `protobuf:"bytes,4,opt,name=Screenshots,proto3" json:"Screenshots,omitempty"`
	Special              *LocalizedString      `protobuf:"bytes,5,opt,name=Special,proto3" json:"Special,omitempty"`
	Friends              *LocalizedString      `protobuf:"bytes,6,opt,name=Friends,proto3" json:"Friends,omitempty"`
	CapsuleGeneric       *LocalizedString      `protobuf:"bytes,7,opt,name=CapsuleGeneric,proto3" json:"CapsuleGeneric,omitempty"`
	CapsuleSmall         *LocalizedString      `protobuf:"bytes,8,opt,name=CapsuleSmall,proto3" json:"CapsuleSmall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetCoverImage() *LocalizedString {
	if m != nil {
		return m.CoverImage
	}
	return nil
}

func (m *Media) GetCoverVideo() *LocalizedString {
	if m != nil {
		return m.CoverVideo
	}
	return nil
}

func (m *Media) GetTrailers() *LocalizedStringArray {
	if m != nil {
		return m.Trailers
	}
	return nil
}

func (m *Media) GetScreenshots() *LocalizedStringArray {
	if m != nil {
		return m.Screenshots
	}
	return nil
}

func (m *Media) GetSpecial() *LocalizedString {
	if m != nil {
		return m.Special
	}
	return nil
}

func (m *Media) GetFriends() *LocalizedString {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *Media) GetCapsuleGeneric() *LocalizedString {
	if m != nil {
		return m.CapsuleGeneric
	}
	return nil
}

func (m *Media) GetCapsuleSmall() *LocalizedString {
	if m != nil {
		return m.CapsuleSmall
	}
	return nil
}

type LocalizedStringArray struct {
	EN                   []string `protobuf:"bytes,1,rep,name=EN,proto3" json:"EN,omitempty"`
	RU                   []string `protobuf:"bytes,2,rep,name=RU,proto3" json:"RU,omitempty"`
	FR                   []string `protobuf:"bytes,3,rep,name=FR,proto3" json:"FR,omitempty"`
	ES                   []string `protobuf:"bytes,4,rep,name=ES,proto3" json:"ES,omitempty"`
	DE                   []string `protobuf:"bytes,5,rep,name=DE,proto3" json:"DE,omitempty"`
	IT                   []string `protobuf:"bytes,6,rep,name=IT,proto3" json:"IT,omitempty"`
	PT                   []string `protobuf:"bytes,7,rep,name=PT,proto3" json:"PT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalizedStringArray) Reset()         { *m = LocalizedStringArray{} }
func (m *LocalizedStringArray) String() string { return proto.CompactTextString(m) }
func (*LocalizedStringArray) ProtoMessage()    {}
func (*LocalizedStringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *LocalizedStringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalizedStringArray.Unmarshal(m, b)
}
func (m *LocalizedStringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalizedStringArray.Marshal(b, m, deterministic)
}
func (m *LocalizedStringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalizedStringArray.Merge(m, src)
}
func (m *LocalizedStringArray) XXX_Size() int {
	return xxx_messageInfo_LocalizedStringArray.Size(m)
}
func (m *LocalizedStringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalizedStringArray.DiscardUnknown(m)
}

var xxx_messageInfo_LocalizedStringArray proto.InternalMessageInfo

func (m *LocalizedStringArray) GetEN() []string {
	if m != nil {
		return m.EN
	}
	return nil
}

func (m *LocalizedStringArray) GetRU() []string {
	if m != nil {
		return m.RU
	}
	return nil
}

func (m *LocalizedStringArray) GetFR() []string {
	if m != nil {
		return m.FR
	}
	return nil
}

func (m *LocalizedStringArray) GetES() []string {
	if m != nil {
		return m.ES
	}
	return nil
}

func (m *LocalizedStringArray) GetDE() []string {
	if m != nil {
		return m.DE
	}
	return nil
}

func (m *LocalizedStringArray) GetIT() []string {
	if m != nil {
		return m.IT
	}
	return nil
}

func (m *LocalizedStringArray) GetPT() []string {
	if m != nil {
		return m.PT
	}
	return nil
}

type Languages struct {
	EN                   *Language `protobuf:"bytes,1,opt,name=EN,proto3" json:"EN,omitempty"`
	RU                   *Language `protobuf:"bytes,2,opt,name=RU,proto3" json:"RU,omitempty"`
	FR                   *Language `protobuf:"bytes,3,opt,name=FR,proto3" json:"FR,omitempty"`
	ES                   *Language `protobuf:"bytes,4,opt,name=ES,proto3" json:"ES,omitempty"`
	DE                   *Language `protobuf:"bytes,5,opt,name=DE,proto3" json:"DE,omitempty"`
	IT                   *Language `protobuf:"bytes,6,opt,name=IT,proto3" json:"IT,omitempty"`
	PT                   *Language `protobuf:"bytes,7,opt,name=PT,proto3" json:"PT,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Languages) Reset()         { *m = Languages{} }
func (m *Languages) String() string { return proto.CompactTextString(m) }
func (*Languages) ProtoMessage()    {}
func (*Languages) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *Languages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Languages.Unmarshal(m, b)
}
func (m *Languages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Languages.Marshal(b, m, deterministic)
}
func (m *Languages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Languages.Merge(m, src)
}
func (m *Languages) XXX_Size() int {
	return xxx_messageInfo_Languages.Size(m)
}
func (m *Languages) XXX_DiscardUnknown() {
	xxx_messageInfo_Languages.DiscardUnknown(m)
}

var xxx_messageInfo_Languages proto.InternalMessageInfo

func (m *Languages) GetEN() *Language {
	if m != nil {
		return m.EN
	}
	return nil
}

func (m *Languages) GetRU() *Language {
	if m != nil {
		return m.RU
	}
	return nil
}

func (m *Languages) GetFR() *Language {
	if m != nil {
		return m.FR
	}
	return nil
}

func (m *Languages) GetES() *Language {
	if m != nil {
		return m.ES
	}
	return nil
}

func (m *Languages) GetDE() *Language {
	if m != nil {
		return m.DE
	}
	return nil
}

func (m *Languages) GetIT() *Language {
	if m != nil {
		return m.IT
	}
	return nil
}

func (m *Languages) GetPT() *Language {
	if m != nil {
		return m.PT
	}
	return nil
}

type Language struct {
	Voice                bool     `protobuf:"varint,1,opt,name=Voice,proto3" json:"Voice,omitempty"`
	Interface            bool     `protobuf:"varint,2,opt,name=Interface,proto3" json:"Interface,omitempty"`
	Subtitles            bool     `protobuf:"varint,3,opt,name=Subtitles,proto3" json:"Subtitles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Language) Reset()         { *m = Language{} }
func (m *Language) String() string { return proto.CompactTextString(m) }
func (*Language) ProtoMessage()    {}
func (*Language) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *Language) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Language.Unmarshal(m, b)
}
func (m *Language) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Language.Marshal(b, m, deterministic)
}
func (m *Language) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Language.Merge(m, src)
}
func (m *Language) XXX_Size() int {
	return xxx_messageInfo_Language.Size(m)
}
func (m *Language) XXX_DiscardUnknown() {
	xxx_messageInfo_Language.DiscardUnknown(m)
}

var xxx_messageInfo_Language proto.InternalMessageInfo

func (m *Language) GetVoice() bool {
	if m != nil {
		return m.Voice
	}
	return false
}

func (m *Language) GetInterface() bool {
	if m != nil {
		return m.Interface
	}
	return false
}

func (m *Language) GetSubtitles() bool {
	if m != nil {
		return m.Subtitles
	}
	return false
}

type Requirements struct {
	Windows              *PlatformRequirements `protobuf:"bytes,1,opt,name=Windows,proto3" json:"Windows,omitempty"`
	MacOs                *PlatformRequirements `protobuf:"bytes,2,opt,name=MacOs,proto3" json:"MacOs,omitempty"`
	Linux                *PlatformRequirements `protobuf:"bytes,3,opt,name=Linux,proto3" json:"Linux,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Requirements) Reset()         { *m = Requirements{} }
func (m *Requirements) String() string { return proto.CompactTextString(m) }
func (*Requirements) ProtoMessage()    {}
func (*Requirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{8}
}

func (m *Requirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requirements.Unmarshal(m, b)
}
func (m *Requirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requirements.Marshal(b, m, deterministic)
}
func (m *Requirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requirements.Merge(m, src)
}
func (m *Requirements) XXX_Size() int {
	return xxx_messageInfo_Requirements.Size(m)
}
func (m *Requirements) XXX_DiscardUnknown() {
	xxx_messageInfo_Requirements.DiscardUnknown(m)
}

var xxx_messageInfo_Requirements proto.InternalMessageInfo

func (m *Requirements) GetWindows() *PlatformRequirements {
	if m != nil {
		return m.Windows
	}
	return nil
}

func (m *Requirements) GetMacOs() *PlatformRequirements {
	if m != nil {
		return m.MacOs
	}
	return nil
}

func (m *Requirements) GetLinux() *PlatformRequirements {
	if m != nil {
		return m.Linux
	}
	return nil
}

type PlatformRequirements struct {
	Minimal              *MachineRequirements `protobuf:"bytes,1,opt,name=Minimal,proto3" json:"Minimal,omitempty"`
	Recommended          *MachineRequirements `protobuf:"bytes,2,opt,name=Recommended,proto3" json:"Recommended,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PlatformRequirements) Reset()         { *m = PlatformRequirements{} }
func (m *PlatformRequirements) String() string { return proto.CompactTextString(m) }
func (*PlatformRequirements) ProtoMessage()    {}
func (*PlatformRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9}
}

func (m *PlatformRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformRequirements.Unmarshal(m, b)
}
func (m *PlatformRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformRequirements.Marshal(b, m, deterministic)
}
func (m *PlatformRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformRequirements.Merge(m, src)
}
func (m *PlatformRequirements) XXX_Size() int {
	return xxx_messageInfo_PlatformRequirements.Size(m)
}
func (m *PlatformRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformRequirements proto.InternalMessageInfo

func (m *PlatformRequirements) GetMinimal() *MachineRequirements {
	if m != nil {
		return m.Minimal
	}
	return nil
}

func (m *PlatformRequirements) GetRecommended() *MachineRequirements {
	if m != nil {
		return m.Recommended
	}
	return nil
}

type MachineRequirements struct {
	System               string   `protobuf:"bytes,1,opt,name=System,proto3" json:"System,omitempty"`
	Processor            string   `protobuf:"bytes,2,opt,name=Processor,proto3" json:"Processor,omitempty"`
	Graphics             string   `protobuf:"bytes,3,opt,name=Graphics,proto3" json:"Graphics,omitempty"`
	Sound                string   `protobuf:"bytes,4,opt,name=Sound,proto3" json:"Sound,omitempty"`
	Ram                  int32    `protobuf:"varint,5,opt,name=Ram,proto3" json:"Ram,omitempty"`
	RamDimension         string   `protobuf:"bytes,6,opt,name=RamDimension,proto3" json:"RamDimension,omitempty"`
	Storage              int32    `protobuf:"varint,7,opt,name=Storage,proto3" json:"Storage,omitempty"`
	StorageDimension     string   `protobuf:"bytes,8,opt,name=StorageDimension,proto3" json:"StorageDimension,omitempty"`
	Other                string   `protobuf:"bytes,9,opt,name=Other,proto3" json:"Other,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MachineRequirements) Reset()         { *m = MachineRequirements{} }
func (m *MachineRequirements) String() string { return proto.CompactTextString(m) }
func (*MachineRequirements) ProtoMessage()    {}
func (*MachineRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{10}
}

func (m *MachineRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MachineRequirements.Unmarshal(m, b)
}
func (m *MachineRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MachineRequirements.Marshal(b, m, deterministic)
}
func (m *MachineRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MachineRequirements.Merge(m, src)
}
func (m *MachineRequirements) XXX_Size() int {
	return xxx_messageInfo_MachineRequirements.Size(m)
}
func (m *MachineRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_MachineRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_MachineRequirements proto.InternalMessageInfo

func (m *MachineRequirements) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func (m *MachineRequirements) GetProcessor() string {
	if m != nil {
		return m.Processor
	}
	return ""
}

func (m *MachineRequirements) GetGraphics() string {
	if m != nil {
		return m.Graphics
	}
	return ""
}

func (m *MachineRequirements) GetSound() string {
	if m != nil {
		return m.Sound
	}
	return ""
}

func (m *MachineRequirements) GetRam() int32 {
	if m != nil {
		return m.Ram
	}
	return 0
}

func (m *MachineRequirements) GetRamDimension() string {
	if m != nil {
		return m.RamDimension
	}
	return ""
}

func (m *MachineRequirements) GetStorage() int32 {
	if m != nil {
		return m.Storage
	}
	return 0
}

func (m *MachineRequirements) GetStorageDimension() string {
	if m != nil {
		return m.StorageDimension
	}
	return ""
}

func (m *MachineRequirements) GetOther() string {
	if m != nil {
		return m.Other
	}
	return ""
}

type Platforms struct {
	Windows              bool     `protobuf:"varint,1,opt,name=Windows,proto3" json:"Windows,omitempty"`
	MacOs                bool     `protobuf:"varint,2,opt,name=MacOs,proto3" json:"MacOs,omitempty"`
	Linux                bool     `protobuf:"varint,3,opt,name=Linux,proto3" json:"Linux,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Platforms) Reset()         { *m = Platforms{} }
func (m *Platforms) String() string { return proto.CompactTextString(m) }
func (*Platforms) ProtoMessage()    {}
func (*Platforms) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{11}
}

func (m *Platforms) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Platforms.Unmarshal(m, b)
}
func (m *Platforms) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Platforms.Marshal(b, m, deterministic)
}
func (m *Platforms) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Platforms.Merge(m, src)
}
func (m *Platforms) XXX_Size() int {
	return xxx_messageInfo_Platforms.Size(m)
}
func (m *Platforms) XXX_DiscardUnknown() {
	xxx_messageInfo_Platforms.DiscardUnknown(m)
}

var xxx_messageInfo_Platforms proto.InternalMessageInfo

func (m *Platforms) GetWindows() bool {
	if m != nil {
		return m.Windows
	}
	return false
}

func (m *Platforms) GetMacOs() bool {
	if m != nil {
		return m.MacOs
	}
	return false
}

func (m *Platforms) GetLinux() bool {
	if m != nil {
		return m.Linux
	}
	return false
}

type LinkObject struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkObject) Reset()         { *m = LinkObject{} }
func (m *LinkObject) String() string { return proto.CompactTextString(m) }
func (*LinkObject) ProtoMessage()    {}
func (*LinkObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{12}
}

func (m *LinkObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkObject.Unmarshal(m, b)
}
func (m *LinkObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkObject.Marshal(b, m, deterministic)
}
func (m *LinkObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkObject.Merge(m, src)
}
func (m *LinkObject) XXX_Size() int {
	return xxx_messageInfo_LinkObject.Size(m)
}
func (m *LinkObject) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkObject.DiscardUnknown(m)
}

var xxx_messageInfo_LinkObject proto.InternalMessageInfo

func (m *LinkObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *LinkObject) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type TagObject struct {
	ID                   string           `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 *LocalizedString `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TagObject) Reset()         { *m = TagObject{} }
func (m *TagObject) String() string { return proto.CompactTextString(m) }
func (*TagObject) ProtoMessage()    {}
func (*TagObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{13}
}

func (m *TagObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagObject.Unmarshal(m, b)
}
func (m *TagObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagObject.Marshal(b, m, deterministic)
}
func (m *TagObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagObject.Merge(m, src)
}
func (m *TagObject) XXX_Size() int {
	return xxx_messageInfo_TagObject.Size(m)
}
func (m *TagObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TagObject.DiscardUnknown(m)
}

var xxx_messageInfo_TagObject proto.InternalMessageInfo

func (m *TagObject) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *TagObject) GetName() *LocalizedString {
	if m != nil {
		return m.Name
	}
	return nil
}

type LocalizedString struct {
	EN                   string   `protobuf:"bytes,1,opt,name=EN,proto3" json:"EN,omitempty"`
	RU                   string   `protobuf:"bytes,2,opt,name=RU,proto3" json:"RU,omitempty"`
	FR                   string   `protobuf:"bytes,3,opt,name=FR,proto3" json:"FR,omitempty"`
	ES                   string   `protobuf:"bytes,4,opt,name=ES,proto3" json:"ES,omitempty"`
	DE                   string   `protobuf:"bytes,5,opt,name=DE,proto3" json:"DE,omitempty"`
	IT                   string   `protobuf:"bytes,6,opt,name=IT,proto3" json:"IT,omitempty"`
	PT                   string   `protobuf:"bytes,7,opt,name=PT,proto3" json:"PT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalizedString) Reset()         { *m = LocalizedString{} }
func (m *LocalizedString) String() string { return proto.CompactTextString(m) }
func (*LocalizedString) ProtoMessage()    {}
func (*LocalizedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{14}
}

func (m *LocalizedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalizedString.Unmarshal(m, b)
}
func (m *LocalizedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalizedString.Marshal(b, m, deterministic)
}
func (m *LocalizedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalizedString.Merge(m, src)
}
func (m *LocalizedString) XXX_Size() int {
	return xxx_messageInfo_LocalizedString.Size(m)
}
func (m *LocalizedString) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalizedString.DiscardUnknown(m)
}

var xxx_messageInfo_LocalizedString proto.InternalMessageInfo

func (m *LocalizedString) GetEN() string {
	if m != nil {
		return m.EN
	}
	return ""
}

func (m *LocalizedString) GetRU() string {
	if m != nil {
		return m.RU
	}
	return ""
}

func (m *LocalizedString) GetFR() string {
	if m != nil {
		return m.FR
	}
	return ""
}

func (m *LocalizedString) GetES() string {
	if m != nil {
		return m.ES
	}
	return ""
}

func (m *LocalizedString) GetDE() string {
	if m != nil {
		return m.DE
	}
	return ""
}

func (m *LocalizedString) GetIT() string {
	if m != nil {
		return m.IT
	}
	return ""
}

func (m *LocalizedString) GetPT() string {
	if m != nil {
		return m.PT
	}
	return ""
}

type GameDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameDeleted) Reset()         { *m = GameDeleted{} }
func (m *GameDeleted) String() string { return proto.CompactTextString(m) }
func (*GameDeleted) ProtoMessage()    {}
func (*GameDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{15}
}

func (m *GameDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameDeleted.Unmarshal(m, b)
}
func (m *GameDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameDeleted.Marshal(b, m, deterministic)
}
func (m *GameDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameDeleted.Merge(m, src)
}
func (m *GameDeleted) XXX_Size() int {
	return xxx_messageInfo_GameDeleted.Size(m)
}
func (m *GameDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_GameDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_GameDeleted proto.InternalMessageInfo

func (m *GameDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*GameObject)(nil), "proto.GameObject")
	proto.RegisterType((*Review)(nil), "proto.Review")
	proto.RegisterType((*Ratings)(nil), "proto.Ratings")
	proto.RegisterType((*RatingInfo)(nil), "proto.RatingInfo")
	proto.RegisterType((*Media)(nil), "proto.Media")
	proto.RegisterType((*LocalizedStringArray)(nil), "proto.LocalizedStringArray")
	proto.RegisterType((*Languages)(nil), "proto.Languages")
	proto.RegisterType((*Language)(nil), "proto.Language")
	proto.RegisterType((*Requirements)(nil), "proto.Requirements")
	proto.RegisterType((*PlatformRequirements)(nil), "proto.PlatformRequirements")
	proto.RegisterType((*MachineRequirements)(nil), "proto.MachineRequirements")
	proto.RegisterType((*Platforms)(nil), "proto.Platforms")
	proto.RegisterType((*LinkObject)(nil), "proto.LinkObject")
	proto.RegisterType((*TagObject)(nil), "proto.TagObject")
	proto.RegisterType((*LocalizedString)(nil), "proto.LocalizedString")
	proto.RegisterType((*GameDeleted)(nil), "proto.GameDeleted")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 1258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x96, 0xcd, 0x72, 0x1b, 0xc5,
	0x13, 0xc0, 0x6b, 0x25, 0xeb, 0xab, 0xe5, 0xd8, 0xce, 0x58, 0xff, 0xd4, 0x54, 0xf2, 0xa7, 0xe2,
	0x5a, 0xa0, 0x50, 0xe5, 0x10, 0x82, 0xf9, 0x08, 0x45, 0x01, 0x55, 0x89, 0x25, 0xbb, 0x54, 0xc4,
	0xb6, 0x32, 0x2b, 0x87, 0x0b, 0x97, 0xf1, 0xaa, 0x2d, 0x0f, 0xec, 0x87, 0x98, 0x59, 0x25, 0x84,
	0x1b, 0x17, 0x0e, 0x5c, 0x78, 0x07, 0xae, 0xbc, 0x09, 0x17, 0x5e, 0x80, 0xa7, 0xe0, 0x09, 0xa8,
	0x99, 0x9d, 0xfd, 0xd0, 0x7a, 0xe5, 0x93, 0xd4, 0xdd, 0xbf, 0x9e, 0xe9, 0x99, 0xed, 0x8f, 0x01,
	0x58, 0xf0, 0x10, 0x1f, 0x2f, 0x65, 0x9c, 0xc4, 0xa4, 0x65, 0x7e, 0xdc, 0x7f, 0xda, 0x00, 0x27,
	0x3c, 0xc4, 0xf3, 0xcb, 0xef, 0xd1, 0x4f, 0xc8, 0x0e, 0x34, 0x26, 0x23, 0xea, 0x1c, 0x38, 0xc3,
	0x1e, 0x6b, 0x4c, 0x46, 0xe4, 0x3d, 0xd8, 0x9a, 0xf1, 0x85, 0xa2, 0x8d, 0x83, 0xe6, 0xb0, 0x7f,
	0xb8, 0x97, 0xfa, 0x3e, 0x9e, 0xf1, 0x45, 0xca, 0x33, 0x63, 0x25, 0x9f, 0x43, 0x7f, 0x84, 0xca,
	0x97, 0x62, 0x99, 0x88, 0x38, 0xa2, 0xcd, 0x03, 0x67, 0xd8, 0x3f, 0xbc, 0x67, 0xe1, 0x17, 0xb1,
	0xcf, 0x03, 0xf1, 0x33, 0xce, 0xbd, 0x44, 0x8a, 0x68, 0xc1, 0xca, 0x28, 0x21, 0xb0, 0x75, 0xc6,
	0x43, 0xa4, 0x5b, 0x66, 0x47, 0xf3, 0x9f, 0x0c, 0xa0, 0x35, 0x13, 0x49, 0x80, 0xb4, 0x65, 0x94,
	0xa9, 0x40, 0x3e, 0x84, 0xde, 0x08, 0x5f, 0x63, 0x10, 0x2f, 0x51, 0xd2, 0xb6, 0xd9, 0xe1, 0x6e,
	0xb6, 0x83, 0x88, 0x7e, 0xb0, 0xf1, 0x14, 0x0c, 0x39, 0x80, 0x3e, 0xc3, 0x00, 0xb9, 0xc2, 0x11,
	0x4f, 0x90, 0x76, 0xcc, 0x62, 0x65, 0x15, 0x79, 0x0c, 0xbd, 0x13, 0x8c, 0x24, 0x9e, 0x72, 0x11,
	0xd1, 0xae, 0x59, 0xf2, 0xe6, 0x09, 0x0b, 0x84, 0x0c, 0xa1, 0x6d, 0x04, 0x45, 0x7b, 0x1b, 0xae,
	0xc3, 0xda, 0xf5, 0xca, 0xd3, 0x80, 0x27, 0x57, 0xb1, 0x0c, 0x15, 0x85, 0xb5, 0x95, 0x73, 0x3d,
	0x2b, 0x10, 0xf2, 0x14, 0xb6, 0x19, 0xfe, 0xb8, 0x12, 0x12, 0x43, 0x8c, 0x12, 0x45, 0xfb, 0xc6,
	0x65, 0xdf, 0xba, 0x94, 0x4d, 0x6c, 0x0d, 0xd4, 0x1b, 0xbd, 0xe0, 0xd1, 0x62, 0xc5, 0x17, 0xa8,
	0xe8, 0xf6, 0xda, 0x46, 0xb9, 0x9e, 0x15, 0x08, 0x39, 0x84, 0xc1, 0x48, 0xa8, 0x65, 0xc0, 0xdf,
	0x32, 0x0c, 0xb9, 0x88, 0x44, 0xb4, 0x98, 0x89, 0x10, 0xe9, 0x9d, 0x03, 0x67, 0xd8, 0x65, 0xb5,
	0x36, 0x32, 0x84, 0xdd, 0x63, 0xe4, 0xc9, 0x4a, 0xa2, 0x3a, 0x8a, 0xa3, 0x44, 0xc6, 0x01, 0xdd,
	0x31, 0x97, 0x59, 0x55, 0x93, 0xfb, 0xd0, 0xcd, 0x54, 0x74, 0xf7, 0xa0, 0x39, 0xec, 0xb1, 0x5c,
	0x26, 0x2e, 0xb4, 0x4e, 0x71, 0x2e, 0x38, 0xdd, 0x33, 0x51, 0x6e, 0xdb, 0x28, 0x8d, 0x8e, 0xa5,
	0x26, 0x32, 0x84, 0x0e, 0xe3, 0x89, 0x88, 0x16, 0x8a, 0xde, 0x35, 0xd4, 0x4e, 0x76, 0x03, 0xa9,
	0x96, 0x65, 0x66, 0xf2, 0x04, 0x3a, 0x33, 0xbe, 0x08, 0x44, 0x84, 0x94, 0xdc, 0x9a, 0x6d, 0x19,
	0xa6, 0x63, 0xd3, 0x79, 0xee, 0x89, 0x04, 0xe9, 0xbe, 0x09, 0x3f, 0x97, 0xc9, 0x07, 0xd0, 0x61,
	0xf8, 0x5a, 0xe0, 0x1b, 0x45, 0x07, 0xe6, 0xcb, 0xde, 0xc9, 0x6f, 0x5e, 0x6b, 0x59, 0x66, 0xd5,
	0x49, 0x38, 0x5d, 0x5d, 0x06, 0x42, 0x5d, 0xa3, 0xa4, 0xff, 0xdb, 0x98, 0x84, 0x39, 0xe3, 0x5e,
	0x41, 0x3b, 0xf5, 0x25, 0xff, 0x87, 0xde, 0x54, 0xa2, 0x52, 0x26, 0xdd, 0xd3, 0x02, 0x2b, 0x14,
	0xba, 0x0e, 0xf4, 0x02, 0xb4, 0x91, 0xd6, 0x81, 0xfe, 0xaf, 0xeb, 0xc0, 0xf3, 0x63, 0x89, 0xa6,
	0x9e, 0x7a, 0x2c, 0x15, 0xb4, 0xf6, 0xe5, 0x2a, 0x4e, 0xb2, 0x92, 0x49, 0x05, 0xf7, 0x2f, 0x27,
	0xbf, 0x3a, 0xf2, 0x3e, 0x6c, 0x4d, 0xc7, 0x27, 0x13, 0xb3, 0x49, 0x11, 0x5f, 0x6a, 0x9d, 0x44,
	0x57, 0x31, 0x33, 0x66, 0x8d, 0x3d, 0x7f, 0x7e, 0x7c, 0x64, 0xb6, 0xac, 0xc7, 0xb4, 0x59, 0x63,
	0x47, 0x63, 0x76, 0x6e, 0x8b, 0xba, 0x0e, 0xd3, 0x66, 0x8d, 0x8d, 0x3d, 0xf6, 0xdc, 0x44, 0x55,
	0x8f, 0x69, 0x33, 0x79, 0x17, 0x9a, 0x17, 0xde, 0x37, 0xa6, 0xb2, 0x6b, 0x29, 0x6d, 0x75, 0xff,
	0x70, 0x00, 0x0a, 0x9d, 0x2e, 0xe4, 0x67, 0x0b, 0x64, 0xa8, 0x12, 0x29, 0xfc, 0xc4, 0x1c, 0xab,
	0xc5, 0xca, 0x2a, 0xf2, 0x04, 0xf6, 0x6d, 0xe6, 0x9e, 0x47, 0xfa, 0x63, 0x9f, 0xc5, 0x89, 0xf0,
	0xd1, 0x9c, 0xac, 0xcb, 0xea, 0x4c, 0x3a, 0xa7, 0xbd, 0xeb, 0xf8, 0x4d, 0x79, 0xdd, 0xa6, 0xa1,
	0xab, 0x6a, 0x72, 0x0f, 0xda, 0x69, 0x2c, 0xf6, 0xc2, 0xad, 0xe4, 0xfe, 0xdd, 0xb4, 0x09, 0x4d,
	0x3e, 0x03, 0x38, 0x8a, 0x5f, 0xa3, 0x9c, 0x84, 0x7c, 0x81, 0xf6, 0xd6, 0x37, 0xa5, 0x63, 0x89,
	0xcc, 0xfd, 0x5e, 0x89, 0x39, 0xc6, 0xf6, 0x33, 0xdc, 0xee, 0x67, 0x48, 0xf2, 0x14, 0xba, 0x33,
	0xc9, 0x45, 0x80, 0x52, 0xd9, 0xaf, 0xf2, 0xa0, 0xde, 0xeb, 0x99, 0x94, 0xfc, 0x2d, 0xcb, 0x61,
	0xf2, 0x15, 0xf4, 0x3d, 0x5f, 0x22, 0x46, 0xea, 0x3a, 0x4e, 0x94, 0xfd, 0x54, 0xb7, 0xfa, 0x96,
	0x79, 0x5d, 0x73, 0xde, 0x12, 0x7d, 0xc1, 0x03, 0xfb, 0xfd, 0x36, 0xd6, 0x9c, 0xc5, 0xb4, 0xc7,
	0xb1, 0x14, 0x18, 0xcd, 0x95, 0xed, 0xd8, 0x1b, 0x3d, 0x2c, 0x46, 0xbe, 0x86, 0x9d, 0x23, 0xbe,
	0x54, 0xab, 0x00, 0x4f, 0x30, 0x42, 0x29, 0x7c, 0xd3, 0xb7, 0x37, 0x3b, 0x56, 0x68, 0xf2, 0x05,
	0x6c, 0x5b, 0x8d, 0x17, 0xf2, 0x20, 0xb0, 0x5d, 0x7d, 0x93, 0xf7, 0x1a, 0xeb, 0xfe, 0xea, 0xc0,
	0xa0, 0xee, 0x16, 0xf4, 0x50, 0x1c, 0x9f, 0x51, 0xc7, 0x34, 0xb4, 0xc6, 0xf8, 0x4c, 0xcb, 0xec,
	0xc2, 0x8c, 0xc4, 0x1e, 0x6b, 0xb0, 0x0b, 0x2d, 0x1f, 0x33, 0xda, 0x4c, 0xe5, 0x63, 0x66, 0x78,
	0x8f, 0x6e, 0x59, 0xde, 0xd3, 0xf2, 0x68, 0x4c, 0x5b, 0xa9, 0x3c, 0x1a, 0x9b, 0x21, 0x3b, 0xa3,
	0xed, 0x54, 0x9e, 0xcc, 0xb4, 0x3c, 0x9d, 0xd1, 0x4e, 0x2a, 0x4f, 0x67, 0xee, 0xbf, 0x4e, 0xa9,
	0xab, 0x93, 0x87, 0x76, 0x77, 0x7d, 0x90, 0xdd, 0x4a, 0x6f, 0x37, 0xe1, 0x3c, 0xb4, 0xe1, 0xd4,
	0x03, 0xec, 0x42, 0x03, 0x26, 0xbe, 0x7a, 0xe0, 0x98, 0x99, 0x2d, 0x3c, 0x9b, 0x0f, 0x35, 0x5b,
	0x78, 0x1a, 0x30, 0x27, 0xa8, 0x07, 0x46, 0x63, 0x0d, 0x98, 0x23, 0xd5, 0x03, 0x93, 0x99, 0x06,
	0xcc, 0x19, 0xeb, 0x81, 0xe9, 0xcc, 0xfd, 0x0e, 0xba, 0x99, 0xac, 0x7b, 0xdc, 0xab, 0x58, 0x57,
	0xb0, 0x63, 0x6a, 0x32, 0x15, 0x74, 0x07, 0x9d, 0x44, 0x09, 0xca, 0x2b, 0x9e, 0xd7, 0x76, 0xa1,
	0xd0, 0x56, 0x6f, 0x75, 0x99, 0xe8, 0xb7, 0x82, 0xb2, 0xb5, 0x5c, 0x28, 0xdc, 0x3f, 0x9d, 0xf5,
	0x09, 0x4b, 0x3e, 0x85, 0xce, 0xb7, 0x22, 0x9a, 0xc7, 0x6f, 0x94, 0xbd, 0xda, 0x07, 0x95, 0xf9,
	0xbc, 0x36, 0x74, 0x33, 0x96, 0x7c, 0x04, 0xad, 0x53, 0xee, 0x9f, 0x2b, 0x7b, 0xdd, 0xb7, 0x3a,
	0xa5, 0xa4, 0x76, 0x79, 0x21, 0xa2, 0xd5, 0x4f, 0x95, 0x5a, 0xad, 0x77, 0x31, 0xa4, 0xfb, 0x9b,
	0x03, 0x83, 0x3a, 0x3b, 0xf9, 0x04, 0x3a, 0xa7, 0x22, 0x12, 0x21, 0x0f, 0x6c, 0xd4, 0xf7, 0xb3,
	0x31, 0xca, 0xfd, 0x6b, 0x11, 0xe1, 0x7a, 0xd0, 0x16, 0x25, 0x5f, 0xea, 0x97, 0x90, 0x1f, 0x87,
	0x21, 0x46, 0x73, 0x9c, 0xdb, 0xd0, 0x6f, 0xf3, 0x2c, 0xe3, 0xee, 0xef, 0x0d, 0xd8, 0xaf, 0x81,
	0x74, 0x63, 0xf4, 0xde, 0xaa, 0x04, 0x43, 0x3b, 0xcd, 0xac, 0x94, 0x0e, 0xba, 0xd8, 0x47, 0xa5,
	0x62, 0x69, 0xe7, 0x59, 0xa1, 0x30, 0x63, 0x58, 0xf2, 0xe5, 0xb5, 0xf0, 0x95, 0x9d, 0x6b, 0xb9,
	0x6c, 0x06, 0x5e, 0xbc, 0x8a, 0xe6, 0xd9, 0x68, 0x33, 0x02, 0xd9, 0x83, 0x26, 0xe3, 0xa1, 0x49,
	0xbe, 0x16, 0xd3, 0x7f, 0x89, 0x0b, 0xdb, 0x8c, 0x87, 0x23, 0x11, 0x62, 0xa4, 0xf4, 0x7b, 0xb3,
	0x6d, 0xf0, 0x35, 0x1d, 0xa1, 0xd0, 0xf1, 0x92, 0x58, 0xea, 0x8e, 0xdc, 0x31, 0x9e, 0x99, 0x48,
	0x1e, 0xc1, 0x9e, 0xfd, 0x5b, 0xac, 0xd0, 0x35, 0x2b, 0xdc, 0xd0, 0xeb, 0x88, 0xce, 0x13, 0x3d,
	0xeb, 0x7b, 0x69, 0x44, 0x46, 0x70, 0x5f, 0x96, 0x5e, 0x77, 0x7a, 0xa3, 0x72, 0x22, 0x75, 0x8b,
	0x5c, 0x19, 0x94, 0x73, 0xa5, 0x9b, 0xa5, 0xc3, 0xa0, 0x9c, 0x0e, 0xdd, 0xec, 0x8b, 0x1f, 0x02,
	0x14, 0x0f, 0x88, 0x1b, 0xaf, 0xf0, 0xfc, 0x45, 0xdc, 0x28, 0xbd, 0x88, 0xdd, 0x13, 0xe8, 0xe5,
	0x2f, 0xcf, 0x1b, 0x2e, 0x8f, 0xec, 0xc3, 0xfa, 0xf6, 0xb1, 0x62, 0x18, 0xf7, 0x17, 0x07, 0x76,
	0x2b, 0x96, 0xbc, 0xe7, 0x39, 0x95, 0x9e, 0xe7, 0x54, 0x7a, 0x9e, 0x53, 0xe9, 0x79, 0x4e, 0xa5,
	0xe7, 0x39, 0x95, 0x9e, 0xe7, 0x54, 0x7a, 0x9e, 0x63, 0x7b, 0xde, 0x3b, 0xd0, 0xd7, 0xcf, 0xb1,
	0x11, 0x06, 0x98, 0xe0, 0xbc, 0x7a, 0x9c, 0xcb, 0xb6, 0x89, 0xff, 0xe3, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xe8, 0x11, 0x91, 0x8b, 0xc2, 0x0c, 0x00, 0x00,
}
